repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.7
  -  repo: https://github.com/pycqa/isort
     rev: 5.10.1
     hooks:
     - id: isort
  -  repo: https://github.com/csachs/pyproject-flake8
     rev: v0.0.1a2.post1
     hooks:
     - id: pyproject-flake8
